package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/adrg/xdg"
	"github.com/gin-gonic/gin"
	"github.com/glebarez/sqlite"
	"github.com/oklog/ulid/v2"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/thisisibrahimd/telesto/apps/telesto-api/internal/config"
	"github.com/thisisibrahimd/telesto/apps/telesto-api/internal/db/query"
	"github.com/thisisibrahimd/telesto/apps/telesto-api/internal/models"
	"gorm.io/gorm"
)

var telestoCfg *config.Config
var gormDb *gorm.DB
var router *gin.Engine

var telestoCmd = &cobra.Command{
	Use: "telesto",
	Run: func(cmd *cobra.Command, args []string) {
	},
}

// ErrorHandler captures errors and returns a consistent JSON error response
func ErrorHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next() // Step1: Process the request first.

		// Step2: Check if any errors were added to the context
		if len(c.Errors) > 0 {
			// Step3: Use the last error
			err := c.Errors.Last().Err

			// Step4: Respond with a generic error message
			c.JSON(http.StatusInternalServerError,
				NewProblemDetails(http.StatusInternalServerError).WithDetail(err.Error()),
			)
		}

		// Any other steps if no errors are found
	}
}

type ProblemDetails struct {
	//   Type is a URI reference [RFC3986] that identifies the
	//   problem type. This specification encourages that, when
	//   dereferenced, it provide human-readable documentation for the
	//   problem type (e.g., using HTML [W3C.REC-html5-20141028]). When
	//   this member is not present, its value is assumed to be
	//   "about:blank".
	Type string `json:"type" xml:"type"`
	//   Title is a short, human-readable summary of the problem
	//   type. It SHOULD NOT change from occurrence to occurrence of the
	//   problem, except for purposes of localization (e.g., using
	//   proactive content negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title" xml:"title"`
	//   Status is the HTTP status code ([RFC7231], Section 6)
	//   generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty" xml:"status,omitempty"`
	//   Detail is a human-readable explanation specific to this
	//   occurrence of the problem. It is empty by default and
	//   it will not be marshalled if empty.
	Detail string `json:"detail,omitempty" xml:"detail,omitempty"`
	//   Instance is a URI reference that identifies the specific
	//   occurrence of the problem. It may or may not yield further
	//   information if dereferenced. It is empty by default and
	//   it will not be marshalled if empty.
	Instance string `json:"instance,omitempty" xml:"instance,omitempty"`
}

func (p *ProblemDetails) WithType(t string) *ProblemDetails {
	p.Type = t
	return p
}

func (p *ProblemDetails) WithTitle(title string) *ProblemDetails {
	p.Title = title
	return p
}

func (p *ProblemDetails) WithStatus(status int) *ProblemDetails {
	p.Status = status
	return p
}

func (p *ProblemDetails) WithDetail(detail string) *ProblemDetails {
	p.Detail = detail
	return p
}

func (p *ProblemDetails) WithInstance(instance string) *ProblemDetails {
	p.Instance = instance
	return p
}
func (p *ProblemDetails) ForGin() (int, *ProblemDetails) {
	return p.Status, p
}

func NewProblemDetails(status int) *ProblemDetails {
	return &ProblemDetails{
		Status: status,
	}
}

func main() {
	// setup config
	telestoCfg = &config.Config{}

	// setup viper
	viperCfg := viper.New()
	viperCfg.SetConfigName("telesto")

	// Add search paths to find the file
	viperCfg.AddConfigPath("/etc/telesto/")
	viperCfg.AddConfigPath(xdg.ConfigHome)
	viperCfg.AddConfigPath(".")

	// setup env config support
	viperCfg.SetEnvPrefix("TL")
	viperCfg.AutomaticEnv()

	// bind config values to cmd flags
	telestoCfg.SetFlags(telestoCmd, viperCfg)

	// define and read command line flags
	telestoCmd.PersistentFlags().StringP("config", "c", "", "config file")
	if err := telestoCmd.ParseFlags(os.Args); err != nil {
		log.Err(err).Msg("unable to read flags")
		return
	}
	configFile, err := telestoCmd.PersistentFlags().GetString("config")
	if err != nil {
		log.Err(err).Msg("unable to read config flag")
		return
	}

	// read config
	if configFile != "" {
		viperCfg.SetConfigFile(configFile)
	}
	if err := viperCfg.ReadInConfig(); err == nil {
		log.Info().Str("file", viperCfg.ConfigFileUsed()).Msg("loaded config file")
	}
	if err := viperCfg.Unmarshal(telestoCfg); err == nil {
		log.Info().Msg("loaded config into memory")
	}

	// setup db
	gormDb, err = gorm.Open(sqlite.Open(telestoCfg.Database.SQLite.File), &gorm.Config{})
	if err != nil {
		log.Err(err).Msg("unable to open sqlite db")
	}

	// migrate db
	if err := gormDb.AutoMigrate(&models.OtelCol{}); err != nil {
		log.Err(err).Msg("database migration failed")
	}

	// setup gorm dao for db
	suppliedQuery := query.Use(gormDb)
	o := suppliedQuery.OtelCol

	// setup http server and routes
	router := gin.Default()
	router.Use(ErrorHandler())
	apiV1Router := router.Group("api/v1")
	{
		otelcol := apiV1Router.Group("otelcol")
		otelcol.GET("/:id", func(ctx *gin.Context) {
			id := ctx.Param("id")
			oc, err := o.WithContext(ctx).Where(o.ID.Eq(id)).First()
			if err != nil {
				ctx.Error(fmt.Errorf("unable to read otelcols: %v", err))
				return
			}
			ctx.JSON(200, oc)
		})
		otelcol.GET("/", func(ctx *gin.Context) {
			oc, err := o.WithContext(ctx).Find()
			if err != nil {
				ctx.Error(fmt.Errorf("unable to read otelcols: %v", err))
				return
			}
			ctx.JSON(200, oc)
		})
		type OtelColPostRequest struct {
			Name string `json:"name"`
		}
		otelcol.POST("/", func(ctx *gin.Context) {
			var request OtelColPostRequest
			if err := ctx.ShouldBindJSON(&request); err != nil {
				ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
				return
			}

			id := ulid.Make().String()
			newOtelCol := &models.OtelCol{
				ID:   id,
				Name: request.Name,
			}
			if err := o.WithContext(ctx).Create(newOtelCol); err != nil {
				ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
				return
			}
			ctx.JSON(201, newOtelCol)
		})
		type OtelColPutRequest struct {
			Name string `json:"name"`
		}
		otelcol.PUT("/:id", func(ctx *gin.Context) {
			id := ctx.Param("id")
			var request OtelColPutRequest
			if err := ctx.ShouldBindJSON(&request); err != nil {
				ctx.JSON(http.StatusBadRequest, NewProblemDetails(http.StatusBadRequest).WithDetail("malformed input"))
				return
			}

			_, err := o.WithContext(ctx).Where(o.ID.Eq(id)).Updates(request)
			if err != nil {
				ctx.Status(400)
			}

			ctx.Status(200)
		})
		otelcol.DELETE("/:id", func(ctx *gin.Context) {
			id := ctx.Param("id")
			_, err := o.WithContext(ctx).Where(o.ID.Eq(id)).Delete()
			if err != nil {
				ctx.Error(fmt.Errorf("deletion failed: %v", err))
				return
			}
			ctx.Status(200)
		})
	}
	apiV1Router.POST("getparams.execute", func(ctx *gin.Context) {
		o := suppliedQuery.OtelCol
		type PluginInputParams struct {
			// The parameters passed in the ApplicationSet spec.generators.plugin.parameters field
			Parameters map[string]interface{} `json:"parameters"`
		}
		type PluginInput struct {
			ApplicationSetName string            `json:"applicationSetName"`
			Input              PluginInputParams `json:"input"`
		}

		type PluginOutputParams struct {
			// Must be a list of object maps. Each map becomes a set of parameters for a new Application.
			Parameters []map[string]interface{} `json:"parameters"`
		}
		// Define the required output structure
		type PluginOutput struct {
			Output PluginOutputParams `json:"output"`
		}

		output := &PluginOutput{
			Output: PluginOutputParams{
				Parameters: []map[string]interface{}{},
			},
		}

		otelcols, _ := o.WithContext(ctx).Find()
		for _, otelcol := range otelcols {
			output.Output.Parameters = append(output.Output.Parameters, map[string]interface{}{
				"otelcol": otelcol.ID,
			})
		}

		ctx.JSON(200, output)

	})

	router.Run(fmt.Sprintf("%s:%d", telestoCfg.Host, telestoCfg.Port)) // listens on 0.0.0.0:8080 by default
	// launch command
	// if err := telestoCmd.Execute(); err != nil {
	// 	fmt.Fprintln(os.Stderr, err)
	// 	os.Exit(1)
	// }
}
