[tools]
go = "1.25.8"
golangci-lint = "2.6.1"
tanka = "0.38.0"
"github:thisisibrahimd/k8s" = "0.4.2"
"github:kubernetes-sigs/cloud-provider-kind" = "0.11.1"
"github:guumaster/hostctl" = "1.1.4"
mkcert = "1.4.4"
