# Define variables
tanka_environment_directory := "./environments"
crd_filter := "--target 'CustomResourceDefinition/.+'"

get-argo-admin-password:
    kubectl get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d | pbcopy

cpk:
    sudo cloud-provider-kind    

tk-lint ENVIRONMENT_NAME:
    tk lint "{{tanka_environment_directory}}/{{ENVIRONMENT_NAME}}"

tk-diff ENVIRONMENT_NAME:
    tk diff "{{tanka_environment_directory}}/{{ENVIRONMENT_NAME}}" 

tk-apply ENVIRONMENT_NAME:
    tk apply "{{tanka_environment_directory}}/{{ENVIRONMENT_NAME}}" --auto-approve always && tk prune "{{tanka_environment_directory}}/{{ENVIRONMENT_NAME}}" 

tk-apply-crds ENVIRONMENT_NAME:
    tk apply "{{tanka_environment_directory}}/{{ENVIRONMENT_NAME}}" --target 'CustomResourceDefinition/.+' --auto-approve always --validate
