// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/thisisibrahimd/telesto/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newOtelcol(db *gorm.DB) otelcol {
	_otelcol := otelcol{}

	_otelcol.otelcolDo.UseDB(db)
	_otelcol.otelcolDo.UseModel(&model.Otelcol{})

	tableName := _otelcol.otelcolDo.TableName()
	_otelcol.ALL = field.NewField(tableName, "*")
	_otelcol.ID = field.NewString(tableName, "id")
	_otelcol.Name = field.NewString(tableName, "name")
	_otelcol.UserID = field.NewString(tableName, "user_id")

	_otelcol.fillFieldMap()

	return _otelcol
}

type otelcol struct {
	otelcolDo otelcolDo

	ALL    field.Field
	ID     field.String
	Name   field.String
	UserID field.String

	fieldMap map[string]field.Expr
}

func (o otelcol) Table(newTableName string) *otelcol {
	o.otelcolDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o otelcol) As(alias string) *otelcol {
	o.otelcolDo.DO = *(o.otelcolDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *otelcol) updateTableName(table string) *otelcol {
	o.ALL = field.NewField(table, "*")
	o.ID = field.NewString(table, "id")
	o.Name = field.NewString(table, "name")
	o.UserID = field.NewString(table, "user_id")

	o.fillFieldMap()

	return o
}

func (o *otelcol) WithContext(ctx context.Context) *otelcolDo { return o.otelcolDo.WithContext(ctx) }

func (o otelcol) TableName() string { return o.otelcolDo.TableName() }

func (o otelcol) Alias() string { return o.otelcolDo.Alias() }

func (o *otelcol) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *otelcol) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 3)
	o.fieldMap["id"] = o.ID
	o.fieldMap["name"] = o.Name
	o.fieldMap["user_id"] = o.UserID
}

func (o otelcol) clone(db *gorm.DB) otelcol {
	o.otelcolDo.ReplaceDB(db)
	return o
}

type otelcolDo struct{ gen.DO }

func (o otelcolDo) Debug() *otelcolDo {
	return o.withDO(o.DO.Debug())
}

func (o otelcolDo) WithContext(ctx context.Context) *otelcolDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o otelcolDo) Clauses(conds ...clause.Expression) *otelcolDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o otelcolDo) Returning(value interface{}, columns ...string) *otelcolDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o otelcolDo) Not(conds ...gen.Condition) *otelcolDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o otelcolDo) Or(conds ...gen.Condition) *otelcolDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o otelcolDo) Select(conds ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o otelcolDo) Where(conds ...gen.Condition) *otelcolDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o otelcolDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *otelcolDo {
	return o.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (o otelcolDo) Order(conds ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o otelcolDo) Distinct(cols ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o otelcolDo) Omit(cols ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o otelcolDo) Join(table schema.Tabler, on ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o otelcolDo) LeftJoin(table schema.Tabler, on ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o otelcolDo) RightJoin(table schema.Tabler, on ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o otelcolDo) Group(cols ...field.Expr) *otelcolDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o otelcolDo) Having(conds ...gen.Condition) *otelcolDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o otelcolDo) Limit(limit int) *otelcolDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o otelcolDo) Offset(offset int) *otelcolDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o otelcolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *otelcolDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o otelcolDo) Unscoped() *otelcolDo {
	return o.withDO(o.DO.Unscoped())
}

func (o otelcolDo) Create(values ...*model.Otelcol) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o otelcolDo) CreateInBatches(values []*model.Otelcol, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o otelcolDo) Save(values ...*model.Otelcol) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o otelcolDo) First() (*model.Otelcol, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Otelcol), nil
	}
}

func (o otelcolDo) Take() (*model.Otelcol, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Otelcol), nil
	}
}

func (o otelcolDo) Last() (*model.Otelcol, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Otelcol), nil
	}
}

func (o otelcolDo) Find() ([]*model.Otelcol, error) {
	result, err := o.DO.Find()
	return result.([]*model.Otelcol), err
}

func (o otelcolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Otelcol, err error) {
	buf := make([]*model.Otelcol, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o otelcolDo) FindInBatches(result *[]*model.Otelcol, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o otelcolDo) Attrs(attrs ...field.AssignExpr) *otelcolDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o otelcolDo) Assign(attrs ...field.AssignExpr) *otelcolDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o otelcolDo) Joins(fields ...field.RelationField) *otelcolDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o otelcolDo) Preload(fields ...field.RelationField) *otelcolDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o otelcolDo) FirstOrInit() (*model.Otelcol, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Otelcol), nil
	}
}

func (o otelcolDo) FirstOrCreate() (*model.Otelcol, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Otelcol), nil
	}
}

func (o otelcolDo) FindByPage(offset int, limit int) (result []*model.Otelcol, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o otelcolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o *otelcolDo) withDO(do gen.Dao) *otelcolDo {
	o.DO = *do.(*gen.DO)
	return o
}
