// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/thisisibrahimd/telesto/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newTelesto(db *gorm.DB) telesto {
	_telesto := telesto{}

	_telesto.telestoDo.UseDB(db)
	_telesto.telestoDo.UseModel(&model.Telesto{})

	tableName := _telesto.telestoDo.TableName()
	_telesto.ALL = field.NewField(tableName, "*")
	_telesto.ID = field.NewString(tableName, "id")
	_telesto.Name = field.NewString(tableName, "name")
	_telesto.UserID = field.NewString(tableName, "user_id")
	_telesto.Tokens = telestoTokens{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tokens", "model.Token"),
		Telesto: struct {
			field.RelationField
			Tokens struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Tokens.Telesto", "model.Telesto"),
			Tokens: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Tokens.Telesto.Tokens", "model.Token"),
			},
		},
	}

	_telesto.fillFieldMap()

	return _telesto
}

type telesto struct {
	telestoDo telestoDo

	ALL    field.Field
	ID     field.String
	Name   field.String
	UserID field.String
	Tokens telestoTokens

	fieldMap map[string]field.Expr
}

func (t telesto) Table(newTableName string) *telesto {
	t.telestoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t telesto) As(alias string) *telesto {
	t.telestoDo.DO = *(t.telestoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *telesto) updateTableName(table string) *telesto {
	t.ALL = field.NewField(table, "*")
	t.ID = field.NewString(table, "id")
	t.Name = field.NewString(table, "name")
	t.UserID = field.NewString(table, "user_id")

	t.fillFieldMap()

	return t
}

func (t *telesto) WithContext(ctx context.Context) *telestoDo { return t.telestoDo.WithContext(ctx) }

func (t telesto) TableName() string { return t.telestoDo.TableName() }

func (t telesto) Alias() string { return t.telestoDo.Alias() }

func (t *telesto) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *telesto) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["user_id"] = t.UserID

}

func (t telesto) clone(db *gorm.DB) telesto {
	t.telestoDo.ReplaceDB(db)
	return t
}

type telestoTokens struct {
	db *gorm.DB

	field.RelationField

	Telesto struct {
		field.RelationField
		Tokens struct {
			field.RelationField
		}
	}
}

func (a telestoTokens) Where(conds ...field.Expr) *telestoTokens {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a telestoTokens) WithContext(ctx context.Context) *telestoTokens {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a telestoTokens) Model(m *model.Telesto) *telestoTokensTx {
	return &telestoTokensTx{a.db.Model(m).Association(a.Name())}
}

type telestoTokensTx struct{ tx *gorm.Association }

func (a telestoTokensTx) Find() (result *model.Token, err error) {
	return result, a.tx.Find(&result)
}

func (a telestoTokensTx) Append(values ...*model.Token) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a telestoTokensTx) Replace(values ...*model.Token) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a telestoTokensTx) Delete(values ...*model.Token) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a telestoTokensTx) Clear() error {
	return a.tx.Clear()
}

func (a telestoTokensTx) Count() int64 {
	return a.tx.Count()
}

type telestoDo struct{ gen.DO }

func (t telestoDo) Debug() *telestoDo {
	return t.withDO(t.DO.Debug())
}

func (t telestoDo) WithContext(ctx context.Context) *telestoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t telestoDo) Clauses(conds ...clause.Expression) *telestoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t telestoDo) Returning(value interface{}, columns ...string) *telestoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t telestoDo) Not(conds ...gen.Condition) *telestoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t telestoDo) Or(conds ...gen.Condition) *telestoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t telestoDo) Select(conds ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t telestoDo) Where(conds ...gen.Condition) *telestoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t telestoDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *telestoDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t telestoDo) Order(conds ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t telestoDo) Distinct(cols ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t telestoDo) Omit(cols ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t telestoDo) Join(table schema.Tabler, on ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t telestoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *telestoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t telestoDo) RightJoin(table schema.Tabler, on ...field.Expr) *telestoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t telestoDo) Group(cols ...field.Expr) *telestoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t telestoDo) Having(conds ...gen.Condition) *telestoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t telestoDo) Limit(limit int) *telestoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t telestoDo) Offset(offset int) *telestoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t telestoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *telestoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t telestoDo) Unscoped() *telestoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t telestoDo) Create(values ...*model.Telesto) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t telestoDo) CreateInBatches(values []*model.Telesto, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t telestoDo) Save(values ...*model.Telesto) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t telestoDo) First() (*model.Telesto, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Telesto), nil
	}
}

func (t telestoDo) Take() (*model.Telesto, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Telesto), nil
	}
}

func (t telestoDo) Last() (*model.Telesto, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Telesto), nil
	}
}

func (t telestoDo) Find() ([]*model.Telesto, error) {
	result, err := t.DO.Find()
	return result.([]*model.Telesto), err
}

func (t telestoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Telesto, err error) {
	buf := make([]*model.Telesto, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t telestoDo) FindInBatches(result *[]*model.Telesto, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t telestoDo) Attrs(attrs ...field.AssignExpr) *telestoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t telestoDo) Assign(attrs ...field.AssignExpr) *telestoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t telestoDo) Joins(fields ...field.RelationField) *telestoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t telestoDo) Preload(fields ...field.RelationField) *telestoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t telestoDo) FirstOrInit() (*model.Telesto, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Telesto), nil
	}
}

func (t telestoDo) FirstOrCreate() (*model.Telesto, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Telesto), nil
	}
}

func (t telestoDo) FindByPage(offset int, limit int) (result []*model.Telesto, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t telestoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t *telestoDo) withDO(do gen.Dao) *telestoDo {
	t.DO = *do.(*gen.DO)
	return t
}
