// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var OtelCol = struct {
	ID   field.String
	Name field.String
}{
	ID:   field.String{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}
