// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"github.com/thisisibrahimd/telesto/apps/telesto-api/internal/models"
	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newOtelCol(db *gorm.DB) otelCol {
	_otelCol := otelCol{}

	_otelCol.otelColDo.UseDB(db)
	_otelCol.otelColDo.UseModel(&models.OtelCol{})

	tableName := _otelCol.otelColDo.TableName()
	_otelCol.ALL = field.NewField(tableName, "*")
	_otelCol.ID = field.NewString(tableName, "id")
	_otelCol.Name = field.NewString(tableName, "name")

	_otelCol.fillFieldMap()

	return _otelCol
}

type otelCol struct {
	otelColDo otelColDo

	ALL  field.Field
	ID   field.String
	Name field.String

	fieldMap map[string]field.Expr
}

func (o otelCol) Table(newTableName string) *otelCol {
	o.otelColDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o otelCol) As(alias string) *otelCol {
	o.otelColDo.DO = *(o.otelColDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *otelCol) updateTableName(table string) *otelCol {
	o.ALL = field.NewField(table, "*")
	o.ID = field.NewString(table, "id")
	o.Name = field.NewString(table, "name")

	o.fillFieldMap()

	return o
}

func (o *otelCol) WithContext(ctx context.Context) *otelColDo { return o.otelColDo.WithContext(ctx) }

func (o otelCol) TableName() string { return o.otelColDo.TableName() }

func (o otelCol) Alias() string { return o.otelColDo.Alias() }

func (o *otelCol) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *otelCol) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 2)
	o.fieldMap["id"] = o.ID
	o.fieldMap["name"] = o.Name
}

func (o otelCol) clone(db *gorm.DB) otelCol {
	o.otelColDo.ReplaceDB(db)
	return o
}

type otelColDo struct{ gen.DO }

func (o otelColDo) Debug() *otelColDo {
	return o.withDO(o.DO.Debug())
}

func (o otelColDo) WithContext(ctx context.Context) *otelColDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o otelColDo) Clauses(conds ...clause.Expression) *otelColDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o otelColDo) Returning(value interface{}, columns ...string) *otelColDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o otelColDo) Not(conds ...gen.Condition) *otelColDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o otelColDo) Or(conds ...gen.Condition) *otelColDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o otelColDo) Select(conds ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o otelColDo) Where(conds ...gen.Condition) *otelColDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o otelColDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *otelColDo {
	return o.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (o otelColDo) Order(conds ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o otelColDo) Distinct(cols ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o otelColDo) Omit(cols ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o otelColDo) Join(table schema.Tabler, on ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o otelColDo) LeftJoin(table schema.Tabler, on ...field.Expr) *otelColDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o otelColDo) RightJoin(table schema.Tabler, on ...field.Expr) *otelColDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o otelColDo) Group(cols ...field.Expr) *otelColDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o otelColDo) Having(conds ...gen.Condition) *otelColDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o otelColDo) Limit(limit int) *otelColDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o otelColDo) Offset(offset int) *otelColDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o otelColDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *otelColDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o otelColDo) Unscoped() *otelColDo {
	return o.withDO(o.DO.Unscoped())
}

func (o otelColDo) Create(values ...*models.OtelCol) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o otelColDo) CreateInBatches(values []*models.OtelCol, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o otelColDo) Save(values ...*models.OtelCol) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o otelColDo) First() (*models.OtelCol, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.OtelCol), nil
	}
}

func (o otelColDo) Take() (*models.OtelCol, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.OtelCol), nil
	}
}

func (o otelColDo) Last() (*models.OtelCol, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.OtelCol), nil
	}
}

func (o otelColDo) Find() ([]*models.OtelCol, error) {
	result, err := o.DO.Find()
	return result.([]*models.OtelCol), err
}

func (o otelColDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OtelCol, err error) {
	buf := make([]*models.OtelCol, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o otelColDo) FindInBatches(result *[]*models.OtelCol, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o otelColDo) Attrs(attrs ...field.AssignExpr) *otelColDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o otelColDo) Assign(attrs ...field.AssignExpr) *otelColDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o otelColDo) Joins(fields ...field.RelationField) *otelColDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o otelColDo) Preload(fields ...field.RelationField) *otelColDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o otelColDo) FirstOrInit() (*models.OtelCol, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.OtelCol), nil
	}
}

func (o otelColDo) FirstOrCreate() (*models.OtelCol, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.OtelCol), nil
	}
}

func (o otelColDo) FindByPage(offset int, limit int) (result []*models.OtelCol, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o otelColDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o *otelColDo) withDO(do gen.Dao) *otelColDo {
	o.DO = *do.(*gen.DO)
	return o
}
