// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package telestos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/thisisibrahimd/telesto/templates/layouts"

type TelestoModel struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	DestinationURL   string `json:"destinationUrl"`
	AuthorizationSet bool   `json:"authorizationSet"`
}

func telemetrygenCommand(telestoID string) string {
	return `telemetrygen traces \
  --otlp-endpoint ` + telestoID + `.t.telesto.test:4318 \
  --otlp-header 'Authorization="Bearer ${TELESTO_AUTH_TOKEN}"' \
  --traces 1 \
  --otlp-http`
}

func envVarsCode(telestoID string) string {
	return `export OTEL_EXPORTER_OTLP_ENDPOINT=https://` + telestoID + `.t.telesto.test:4318
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer ${TELESTO_AUTH_TOKEN}"`
}

func otlpConfigCode(telestoID string) string {
	return `receivers:
  ...

processors:
  ...

exporters:
  otlp_http/telesto:
    endpoint: https://` + telestoID + `.t.telesto.test:4318
    headers:
      Authorization: "Bearer ${TELESTO_AUTH_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [...]
      processors: [...]
      exporters: [otlp_http/telesto]`
}

func Show(telesto TelestoModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mb-6\"><a href=\"/telestos\" class=\"text-sm text-indigo-600 hover:text-indigo-900\">&larr; Back to Telestos</a></div><div class=\"bg-white rounded-lg shadow p-6\"><h2 class=\"text-2xl font-bold text-gray-900 mb-6\">Telesto Details</h2><dl class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\"><div><dt class=\"text-sm font-medium text-gray-500\">ID</dt><dd class=\"mt-1 text-sm font-mono text-gray-900\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(telesto.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 56, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</dd></div><div><dt class=\"text-sm font-medium text-gray-500\">Name</dt><dd class=\"mt-1 text-sm text-gray-900\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(telesto.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 60, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</dd></div></dl><dl class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\"><div><dt class=\"text-sm font-medium text-gray-500\">Destination URL</dt><dd class=\"mt-1 text-sm font-mono text-gray-900\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(telesto.DestinationURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 66, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</dd></div><div><dt class=\"text-sm font-medium text-gray-500\">Authorization Header</dt>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if telesto.AuthorizationSet {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<dd class=\"mt-1 text-sm font-mono text-gray-900\">SET</dd>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<dd class=\"mt-1 text-sm font-mono text-gray-900\">UNSET</dd>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></dl><div class=\"mt-6 flex items-center gap-3\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 templ.SafeURL
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs("/telestos/" + telesto.ID + "/edit")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 78, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" class=\"inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors\">Edit</a> <button hx-delete=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs("/telestos/" + telesto.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 79, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" hx-target=\"body\" hx-confirm=\"Delete this Telesto?\" class=\"inline-flex items-center px-4 py-2 text-sm font-medium text-red-700 bg-red-50 rounded-lg hover:bg-red-100 transition-colors\">Delete</button></div></div><div class=\"bg-white rounded-lg shadow p-6 mt-6\"><h2 class=\"text-lg font-semibold text-gray-900 mb-4\">Send Traces</h2><div x-data=\"{ tab: 'telemetrygen' }\"><div class=\"flex border-b border-gray-200 mb-4\"><button @click=\"tab = 'telemetrygen'\" :class=\"tab === 'telemetrygen' ? 'border-indigo-500 text-indigo-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'\" class=\"px-4 py-2 text-sm font-medium border-b-2 transition-colors\">telemetrygen</button> <button @click=\"tab = 'otelcol'\" :class=\"tab === 'otelcol' ? 'border-indigo-500 text-indigo-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'\" class=\"px-4 py-2 text-sm font-medium border-b-2 transition-colors\">otelcol</button> <button @click=\"tab = 'otel-instrumentation'\" :class=\"tab === 'otel-instrumentation' ? 'border-indigo-500 text-indigo-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'\" class=\"px-4 py-2 text-sm font-medium border-b-2 transition-colors\">otel instrumentation</button></div><div x-show=\"tab === 'telemetrygen'\"><div class=\"relative\" x-data=\"{ copied: false }\"><button @click=\"copied = true; navigator.clipboard.writeText($refs.code.textContent); setTimeout(() => copied = false, 2000)\" class=\"absolute top-2 right-2 text-xs text-gray-500 hover:text-gray-700 bg-gray-200 rounded px-2 py-1 transition-colors\"><span x-show=\"!copied\">Copy</span> <span x-show=\"copied\">Copied!</span></button><pre x-ref=\"code\" class=\"bg-gray-50 rounded-lg p-4 pr-16 text-sm text-gray-900 whitespace-pre-wrap\"><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(telemetrygenCommand(telesto.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 109, Col: 145}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</code></pre></div></div><div x-show=\"tab === 'otelcol'\"><div class=\"relative\" x-data=\"{ copied: false }\"><button @click=\"copied = true; navigator.clipboard.writeText($refs.code.textContent); setTimeout(() => copied = false, 2000)\" class=\"absolute top-2 right-2 text-xs text-gray-500 hover:text-gray-700 bg-gray-200 rounded px-2 py-1 transition-colors\"><span x-show=\"!copied\">Copy</span> <span x-show=\"copied\">Copied!</span></button><pre x-ref=\"code\" class=\"bg-gray-50 rounded-lg p-4 pr-16 text-sm text-gray-900 whitespace-pre-wrap\"><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(otlpConfigCode(telesto.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 119, Col: 140}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</code></pre></div></div><div x-show=\"tab === 'otel-instrumentation'\"><div class=\"relative\" x-data=\"{ copied: false }\"><button @click=\"copied = true; navigator.clipboard.writeText($refs.code.textContent); setTimeout(() => copied = false, 2000)\" class=\"absolute top-2 right-2 text-xs text-gray-500 hover:text-gray-700 bg-gray-200 rounded px-2 py-1 transition-colors\"><span x-show=\"!copied\">Copy</span> <span x-show=\"copied\">Copied!</span></button><pre x-ref=\"code\" class=\"bg-gray-50 rounded-lg p-4 pr-16 text-sm text-gray-900 whitespace-pre-wrap\"><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(envVarsCode(telesto.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/telestos/show.templ`, Line: 129, Col: 136}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</code></pre></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Console("Telesto | Telestos").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
