directory: charts
repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: nginx
  url: oci://ghcr.io/nginx/charts
- name: dex
  url: https://charts.dexidp.io
- name: external-secrets
  url: https://charts.external-secrets.io
- name: stakater
  url: https://stakater.github.io/stakater-charts
- name: ory
  url: https://k8s.ory.com/helm/charts
- name: grafana
  url: oci://ghcr.io/grafana/helm-charts
- name: grafana-community
  url: oci://ghcr.io/grafana-community/helm-charts
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
requires:
- chart: jetstack/cert-manager
  version: v1.21.1
- chart: argo/argo-cd
  version: 10.3.3
- chart: ory/kratos
  version: 0.63.0
- chart: cnpg/cloudnative-pg
  version: 0.29.0
- chart: cnpg/cluster
  version: 0.8.1
- chart: nginx/nginx-gateway-fabric
  version: 2.6.7
- chart: dex/dex
  version: 0.24.1
- chart: external-secrets/external-secrets
  version: 2.9.0
- chart: jetstack/trust-manager
  version: v0.24.0
- chart: stakater/reloader
  version: 2.2.16
- chart: grafana/grafana-operator
  version: 5.25.0
- chart: grafana-community/loki
  version: 18.11.7
- chart: grafana-community/tempo
  version: 2.3.0
- chart: open-telemetry/opentelemetry-operator
  version: 0.122.0
version: 1
