{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='bundle', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Bundle', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'trust.cert-manager.io/v1alpha1',
    kind: 'Bundle',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"spec represents the desired state of the Bundle resource."'),
  spec: {
    '#sources':: d.obj(help='"sources is a set of references to data whose data will sync to the target."'),
    sources: {
      '#configMap':: d.obj(help="\"configMap is a reference (by name) to a ConfigMap's `data` key(s), or to a\\nlist of ConfigMap's `data` key(s) using label selector, in the trust namespace.\""),
      configMap: {
        '#selector':: d.obj(help='"selector is the label selector to use to fetch a list of objects. Must not be set\\nwhen `name` is set."'),
        selector: {
          '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
          matchExpressions: {
            '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
            withOperator(operator): { operator: operator },
            '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
            withValues(values): { values: if std.isArray(v=values) then values else [values] },
            '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
            withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
          },
          '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressions(matchExpressions): { configMap+: { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
          '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressionsMixin(matchExpressions): { configMap+: { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
          '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { configMap+: { selector+: { matchLabels: matchLabels } } },
          '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { configMap+: { selector+: { matchLabels+: matchLabels } } },
        },
        '#withIncludeAllKeys':: d.fn(help="\"includeAllKeys is a flag to include all keys in the object's `data` field to be used. False by default.\\nThis field must not be true when `key` is set.\"", args=[d.arg(name='includeAllKeys', type=d.T.boolean)]),
        withIncludeAllKeys(includeAllKeys): { configMap+: { includeAllKeys: includeAllKeys } },
        '#withKey':: d.fn(help="\"key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { configMap+: { key: key } },
        '#withName':: d.fn(help='"name is the name of the source object in the trust namespace.\\nThis field must be left empty when `selector` is set"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { configMap+: { name: name } },
      },
      '#secret':: d.obj(help="\"secret is a reference (by name) to a Secret's `data` key(s), or to a\\nlist of Secret's `data` key(s) using label selector, in the trust namespace.\""),
      secret: {
        '#selector':: d.obj(help='"selector is the label selector to use to fetch a list of objects. Must not be set\\nwhen `name` is set."'),
        selector: {
          '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
          matchExpressions: {
            '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
            withOperator(operator): { operator: operator },
            '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
            withValues(values): { values: if std.isArray(v=values) then values else [values] },
            '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
            withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
          },
          '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressions(matchExpressions): { secret+: { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
          '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressionsMixin(matchExpressions): { secret+: { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
          '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { secret+: { selector+: { matchLabels: matchLabels } } },
          '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { secret+: { selector+: { matchLabels+: matchLabels } } },
        },
        '#withIncludeAllKeys':: d.fn(help="\"includeAllKeys is a flag to include all keys in the object's `data` field to be used. False by default.\\nThis field must not be true when `key` is set.\"", args=[d.arg(name='includeAllKeys', type=d.T.boolean)]),
        withIncludeAllKeys(includeAllKeys): { secret+: { includeAllKeys: includeAllKeys } },
        '#withKey':: d.fn(help="\"key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { secret+: { key: key } },
        '#withName':: d.fn(help='"name is the name of the source object in the trust namespace.\\nThis field must be left empty when `selector` is set"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { secret+: { name: name } },
      },
      '#withInLine':: d.fn(help='"inLine is a simple string to append as the source data."', args=[d.arg(name='inLine', type=d.T.string)]),
      withInLine(inLine): { inLine: inLine },
      '#withUseDefaultCAs':: d.fn(help='"useDefaultCAs indicates whether the default CA bundle should be used as a source.\\nThe default CA bundle is available only if trust-manager was installed with\\ndefault CA support enabled, either via the Helm chart or by starting the\\ntrust-manager controller with the \\"--default-package-location\\" flag.\\nIf default CA support was not enabled at startup, setting this field to true\\nwill result in reconciliation failure.\\nThe version of the default CA package used for this Bundle is reported in\\nstatus.defaultCAVersion."', args=[d.arg(name='useDefaultCAs', type=d.T.boolean)]),
      withUseDefaultCAs(useDefaultCAs): { useDefaultCAs: useDefaultCAs },
    },
    '#target':: d.obj(help='"target is the target location in all namespaces to sync source data to."'),
    target: {
      '#additionalFormats':: d.obj(help='"additionalFormats specifies any additional formats to write to the target"'),
      additionalFormats: {
        '#jks':: d.obj(help='"jks requests a JKS-formatted binary trust bundle to be written to the target.\\nThe bundle has \\"changeit\\" as the default password.\\nFor more information refer to this link https://cert-manager.io/docs/faq/#keystore-passwords\\nFormat is deprecated: Writing JKS is subject for removal. Please migrate to PKCS12.\\nPKCS#12 trust stores created by trust-manager are compatible with Java."'),
        jks: {
          '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { target+: { additionalFormats+: { jks+: { key: key } } } } },
          '#withPassword':: d.fn(help='"password for JKS trust store"', args=[d.arg(name='password', type=d.T.string)]),
          withPassword(password): { spec+: { target+: { additionalFormats+: { jks+: { password: password } } } } },
        },
        '#pkcs12':: d.obj(help='"pkcs12 requests a PKCS12-formatted binary trust bundle to be written to the target.\\n\\nThe bundle is by default created without a password.\\nFor more information refer to this link https://cert-manager.io/docs/faq/#keystore-passwords"'),
        pkcs12: {
          '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { target+: { additionalFormats+: { pkcs12+: { key: key } } } } },
          '#withPassword':: d.fn(help='"password for PKCS12 trust store"', args=[d.arg(name='password', type=d.T.string)]),
          withPassword(password): { spec+: { target+: { additionalFormats+: { pkcs12+: { password: password } } } } },
          '#withProfile':: d.fn(help='"profile specifies the certificate encryption algorithms and the HMAC algorithm\\nused to create the PKCS12 trust store.\\n\\nIf provided, allowed values are:\\n`LegacyRC2`: Deprecated. Not supported by default in OpenSSL 3 or Java 20.\\n`LegacyDES`: Less secure algorithm. Use this option for maximal compatibility.\\n`Modern2023`: Secure algorithm. Use this option in case you have to always use secure algorithms (e.g. because of company policy).\\n\\nDefault value is `LegacyRC2` for backward compatibility."', args=[d.arg(name='profile', type=d.T.string)]),
          withProfile(profile): { spec+: { target+: { additionalFormats+: { pkcs12+: { profile: profile } } } } },
        },
      },
      '#configMap':: d.obj(help='"configMap is the target ConfigMap in Namespaces that all Bundle source\\ndata will be synced to."'),
      configMap: {
        '#metadata':: d.obj(help='"metadata is an optional set of labels and annotations to be copied to the target."'),
        metadata: {
          '#withAnnotations':: d.fn(help='"annotations is a key value map to be copied to the target."', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotations(annotations): { spec+: { target+: { configMap+: { metadata+: { annotations: annotations } } } } },
          '#withAnnotationsMixin':: d.fn(help='"annotations is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotationsMixin(annotations): { spec+: { target+: { configMap+: { metadata+: { annotations+: annotations } } } } },
          '#withLabels':: d.fn(help='"labels is a key value map to be copied to the target."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { spec+: { target+: { configMap+: { metadata+: { labels: labels } } } } },
          '#withLabelsMixin':: d.fn(help='"labels is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { spec+: { target+: { configMap+: { metadata+: { labels+: labels } } } } },
        },
        '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { target+: { configMap+: { key: key } } } },
      },
      '#namespaceSelector':: d.obj(help='"namespaceSelector will, if set, only sync the target resource in\\nNamespaces which match the selector."'),
      namespaceSelector: {
        '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
        matchExpressions: {
          '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressions(matchExpressions): { spec+: { target+: { namespaceSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } },
        '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressionsMixin(matchExpressions): { spec+: { target+: { namespaceSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } },
        '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { target+: { namespaceSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { target+: { namespaceSelector+: { matchLabels+: matchLabels } } } },
      },
      '#secret':: d.obj(help='"secret is the target Secret that all Bundle source data will be synced to.\\nUsing Secrets as targets is only supported if enabled at trust-manager startup.\\nBy default, trust-manager has no permissions for writing to secrets and can only read secrets in the trust namespace."'),
      secret: {
        '#metadata':: d.obj(help='"metadata is an optional set of labels and annotations to be copied to the target."'),
        metadata: {
          '#withAnnotations':: d.fn(help='"annotations is a key value map to be copied to the target."', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotations(annotations): { spec+: { target+: { secret+: { metadata+: { annotations: annotations } } } } },
          '#withAnnotationsMixin':: d.fn(help='"annotations is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotationsMixin(annotations): { spec+: { target+: { secret+: { metadata+: { annotations+: annotations } } } } },
          '#withLabels':: d.fn(help='"labels is a key value map to be copied to the target."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { spec+: { target+: { secret+: { metadata+: { labels: labels } } } } },
          '#withLabelsMixin':: d.fn(help='"labels is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { spec+: { target+: { secret+: { metadata+: { labels+: labels } } } } },
        },
        '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { target+: { secret+: { key: key } } } },
      },
    },
    '#withSources':: d.fn(help='"sources is a set of references to data whose data will sync to the target."', args=[d.arg(name='sources', type=d.T.array)]),
    withSources(sources): { spec+: { sources: if std.isArray(v=sources) then sources else [sources] } },
    '#withSourcesMixin':: d.fn(help='"sources is a set of references to data whose data will sync to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sources', type=d.T.array)]),
    withSourcesMixin(sources): { spec+: { sources+: if std.isArray(v=sources) then sources else [sources] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
