// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value *interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// Otelcol defines model for Otelcol.
type Otelcol struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Id     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// OtelcolListResponseBodyItems defines model for OtelcolListResponseBodyItems.
type OtelcolListResponseBodyItems struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string    `json:"$schema,omitempty"`
	Items  *[]Otelcol `json:"items"`
}

// OtelcolPostRequestBody defines model for OtelcolPostRequestBody.
type OtelcolPostRequestBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// OtelcolPutRequestBody defines model for OtelcolPutRequestBody.
type OtelcolPutRequestBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// PluginInput defines model for PluginInput.
type PluginInput struct {
	// Schema A URL to the JSON Schema for this object.
	Schema             *string            `json:"$schema,omitempty"`
	ApplicationSetName *string            `json:"applicationSetName,omitempty"`
	Input              *PluginInputParams `json:"input,omitempty"`
}

// PluginInputParams defines model for PluginInputParams.
type PluginInputParams struct {
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
}

// PluginOutput defines model for PluginOutput.
type PluginOutput struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string             `json:"$schema,omitempty"`
	Output *PluginOutputParams `json:"output,omitempty"`
}

// PluginOutputParams defines model for PluginOutputParams.
type PluginOutputParams struct {
	Parameters *[]map[string]interface{} `json:"parameters"`
}

// GetParamsJSONRequestBody defines body for GetParams for application/json ContentType.
type GetParamsJSONRequestBody = PluginInput

// CreateOtelcolJSONRequestBody defines body for CreateOtelcol for application/json ContentType.
type CreateOtelcolJSONRequestBody = OtelcolPostRequestBody

// UpdateOtelcolJSONRequestBody defines body for UpdateOtelcol for application/json ContentType.
type UpdateOtelcolJSONRequestBody = OtelcolPutRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetParamsWithBody request with any body
	GetParamsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetParams(ctx context.Context, body GetParamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListOtelcol request
	ListOtelcol(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOtelcolWithBody request with any body
	CreateOtelcolWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOtelcol(ctx context.Context, body CreateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteOtelcol request
	DeleteOtelcol(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOtelcol request
	GetOtelcol(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateOtelcolWithBody request with any body
	UpdateOtelcolWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateOtelcol(ctx context.Context, id string, body UpdateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetParamsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetParamsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetParams(ctx context.Context, body GetParamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetParamsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListOtelcol(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListOtelcolRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOtelcolWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOtelcolRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOtelcol(ctx context.Context, body CreateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOtelcolRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteOtelcol(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteOtelcolRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOtelcol(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOtelcolRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateOtelcolWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateOtelcolRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateOtelcol(ctx context.Context, id string, body UpdateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateOtelcolRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetParamsRequest calls the generic GetParams builder with application/json body
func NewGetParamsRequest(server string, body GetParamsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetParamsRequestWithBody(server, "application/json", bodyReader)
}

// NewGetParamsRequestWithBody generates requests for GetParams with any type of body
func NewGetParamsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/getparams.execute/getparams.execute")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListOtelcolRequest generates requests for ListOtelcol
func NewListOtelcolRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/otelcol/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateOtelcolRequest calls the generic CreateOtelcol builder with application/json body
func NewCreateOtelcolRequest(server string, body CreateOtelcolJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOtelcolRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOtelcolRequestWithBody generates requests for CreateOtelcol with any type of body
func NewCreateOtelcolRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/otelcol/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteOtelcolRequest generates requests for DeleteOtelcol
func NewDeleteOtelcolRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/otelcol/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOtelcolRequest generates requests for GetOtelcol
func NewGetOtelcolRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/otelcol/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateOtelcolRequest calls the generic UpdateOtelcol builder with application/json body
func NewUpdateOtelcolRequest(server string, id string, body UpdateOtelcolJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateOtelcolRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateOtelcolRequestWithBody generates requests for UpdateOtelcol with any type of body
func NewUpdateOtelcolRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/otelcol/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetParamsWithBodyWithResponse request with any body
	GetParamsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetParamsResponse, error)

	GetParamsWithResponse(ctx context.Context, body GetParamsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetParamsResponse, error)

	// ListOtelcolWithResponse request
	ListOtelcolWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOtelcolResponse, error)

	// CreateOtelcolWithBodyWithResponse request with any body
	CreateOtelcolWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOtelcolResponse, error)

	CreateOtelcolWithResponse(ctx context.Context, body CreateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOtelcolResponse, error)

	// DeleteOtelcolWithResponse request
	DeleteOtelcolWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteOtelcolResponse, error)

	// GetOtelcolWithResponse request
	GetOtelcolWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetOtelcolResponse, error)

	// UpdateOtelcolWithBodyWithResponse request with any body
	UpdateOtelcolWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOtelcolResponse, error)

	UpdateOtelcolWithResponse(ctx context.Context, id string, body UpdateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOtelcolResponse, error)
}

type GetParamsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *PluginOutput
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetParamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetParamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListOtelcolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *OtelcolListResponseBodyItems
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ListOtelcolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListOtelcolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOtelcolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Otelcol
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CreateOtelcolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOtelcolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteOtelcolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r DeleteOtelcolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteOtelcolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOtelcolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Otelcol
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetOtelcolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOtelcolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateOtelcolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r UpdateOtelcolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateOtelcolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetParamsWithBodyWithResponse request with arbitrary body returning *GetParamsResponse
func (c *ClientWithResponses) GetParamsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetParamsResponse, error) {
	rsp, err := c.GetParamsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetParamsResponse(rsp)
}

func (c *ClientWithResponses) GetParamsWithResponse(ctx context.Context, body GetParamsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetParamsResponse, error) {
	rsp, err := c.GetParams(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetParamsResponse(rsp)
}

// ListOtelcolWithResponse request returning *ListOtelcolResponse
func (c *ClientWithResponses) ListOtelcolWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOtelcolResponse, error) {
	rsp, err := c.ListOtelcol(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListOtelcolResponse(rsp)
}

// CreateOtelcolWithBodyWithResponse request with arbitrary body returning *CreateOtelcolResponse
func (c *ClientWithResponses) CreateOtelcolWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOtelcolResponse, error) {
	rsp, err := c.CreateOtelcolWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOtelcolResponse(rsp)
}

func (c *ClientWithResponses) CreateOtelcolWithResponse(ctx context.Context, body CreateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOtelcolResponse, error) {
	rsp, err := c.CreateOtelcol(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOtelcolResponse(rsp)
}

// DeleteOtelcolWithResponse request returning *DeleteOtelcolResponse
func (c *ClientWithResponses) DeleteOtelcolWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteOtelcolResponse, error) {
	rsp, err := c.DeleteOtelcol(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteOtelcolResponse(rsp)
}

// GetOtelcolWithResponse request returning *GetOtelcolResponse
func (c *ClientWithResponses) GetOtelcolWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetOtelcolResponse, error) {
	rsp, err := c.GetOtelcol(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOtelcolResponse(rsp)
}

// UpdateOtelcolWithBodyWithResponse request with arbitrary body returning *UpdateOtelcolResponse
func (c *ClientWithResponses) UpdateOtelcolWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOtelcolResponse, error) {
	rsp, err := c.UpdateOtelcolWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateOtelcolResponse(rsp)
}

func (c *ClientWithResponses) UpdateOtelcolWithResponse(ctx context.Context, id string, body UpdateOtelcolJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOtelcolResponse, error) {
	rsp, err := c.UpdateOtelcol(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateOtelcolResponse(rsp)
}

// ParseGetParamsResponse parses an HTTP response from a GetParamsWithResponse call
func ParseGetParamsResponse(rsp *http.Response) (*GetParamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetParamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PluginOutput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListOtelcolResponse parses an HTTP response from a ListOtelcolWithResponse call
func ParseListOtelcolResponse(rsp *http.Response) (*ListOtelcolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListOtelcolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OtelcolListResponseBodyItems
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateOtelcolResponse parses an HTTP response from a CreateOtelcolWithResponse call
func ParseCreateOtelcolResponse(rsp *http.Response) (*CreateOtelcolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOtelcolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Otelcol
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteOtelcolResponse parses an HTTP response from a DeleteOtelcolWithResponse call
func ParseDeleteOtelcolResponse(rsp *http.Response) (*DeleteOtelcolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteOtelcolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetOtelcolResponse parses an HTTP response from a GetOtelcolWithResponse call
func ParseGetOtelcolResponse(rsp *http.Response) (*GetOtelcolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOtelcolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Otelcol
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateOtelcolResponse parses an HTTP response from a UpdateOtelcolWithResponse call
func ParseUpdateOtelcolResponse(rsp *http.Response) (*UpdateOtelcolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateOtelcolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
