
pb_data_dir := "internal/pocketbase/pb_data"

nuke_pb_data:
    rm -rf {{pb_data_dir}}

pb_start:
    go run . serve  --dir "{{pb_data_dir}}"

pb_migrate *ARGS:
    go run . migrate {{ARGS}} --dir "{{pb_data_dir}}"

goreleaser *ARGS:
    GORELEASER_PREVIOUS_TAG=$(git tag -l "telesto-pb/v*" | choose -f "/" -o / 1 | sort -r | head -2 | tail -1) GORELEASER_CURRENT_TAG=$(git tag -l "telesto-pb/v*" | choose -f "/" -o / 1 | sort -r | head -1) goreleaser {{ARGS}}
