{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='clusterBundle', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ClusterBundle', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'trust-manager.io/v1alpha2',
    kind: 'ClusterBundle',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"spec represents the desired state of the ClusterBundle resource."'),
  spec: {
    '#defaultCAs':: d.obj(help='"defaultCAs configures the use of a default CA bundle as a trust source."'),
    defaultCAs: {
      '#withProvider':: d.fn(help='"provider identifies the provider of the default CA bundle.\\n\\nValid values:\\n- System: Uses the default CA package made available to trust-manager at startup.\\n     The default CA bundle is available only if trust-manager was installed with\\n\\t\\tdefault CA support enabled, either via the Helm chart or by starting the\\n\\t\\ttrust-manager controller with the \\"--default-package-location\\" flag.\\n\\n\\t\\tIf no default CA package was configured at startup, specifying this source\\n\\t\\twill result in reconciliation failure.\\n\\n\\t\\tThe version of the default CA package used for this Bundle is reported in\\n\\t\\tstatus.defaultCAVersion.\\n- Disabled: No default CAs are used as sources."', args=[d.arg(name='provider', type=d.T.string)]),
      withProvider(provider): { spec+: { defaultCAs+: { provider: provider } } },
    },
    '#sourceRefs':: d.obj(help='"sourceRefs is a list of references to resources whose data will be appended and synced into\\nthe bundle target resources."'),
    sourceRefs: {
      '#selector':: d.obj(help='"selector is the label selector to use to fetch a list of objects. Must not be set\\nwhen `name` is set."'),
      selector: {
        '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
        matchExpressions: {
          '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressions(matchExpressions): { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
        '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressionsMixin(matchExpressions): { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
        '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { selector+: { matchLabels: matchLabels } },
        '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { selector+: { matchLabels+: matchLabels } },
      },
      '#withKey':: d.fn(help="\"key specifies one or more keys in the object's data field to be used.\\nThe \\\"*\\\" wildcard matches any sequence of characters within a key.\\nA value of \\\"*\\\" matches all entries in the data field.\"", args=[d.arg(name='key', type=d.T.string)]),
      withKey(key): { key: key },
      '#withKind':: d.fn(help='"kind is the kind of the source object."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { kind: kind },
      '#withName':: d.fn(help='"name is the name of the source object in the trust namespace.\\nThis field must be left empty when `selector` is set"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
    },
    '#target':: d.obj(help='"target is the target location in all namespaces to sync source data to."'),
    target: {
      '#configMap':: d.obj(help='"configMap is the target ConfigMap in Namespaces that all Bundle source data will be synced to."'),
      configMap: {
        '#data':: d.obj(help="\"data is the specification of the object's `data` field.\""),
        data: {
          '#withFormat':: d.fn(help='"format defines the format of the target value.\\nThe default format is PEM."', args=[d.arg(name='format', type=d.T.string)]),
          withFormat(format): { format: format },
          '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withPassword':: d.fn(help='"password for PKCS12 trust store.\\nBy default, no password is used (password-less PKCS#12)."', args=[d.arg(name='password', type=d.T.string)]),
          withPassword(password): { password: password },
          '#withProfile':: d.fn(help='"profile specifies the certificate encryption algorithms and the HMAC algorithm\\nused to create the PKCS12 trust store.\\n\\nIf provided, allowed values are:\\n`LegacyRC2`: Deprecated. Not supported by default in OpenSSL 3 or Java 20.\\n`LegacyDES`: Less secure algorithm. Use this option for maximal compatibility.\\n`Modern2023`: Secure algorithm. Use this option in case you have to always use secure algorithms (e.g. because of company policy).\\n\\nDefault value is `LegacyDES`."', args=[d.arg(name='profile', type=d.T.string)]),
          withProfile(profile): { profile: profile },
        },
        '#metadata':: d.obj(help='"metadata is an optional set of labels and annotations to be copied to the target."'),
        metadata: {
          '#withAnnotations':: d.fn(help='"annotations is a key value map to be copied to the target."', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotations(annotations): { spec+: { target+: { configMap+: { metadata+: { annotations: annotations } } } } },
          '#withAnnotationsMixin':: d.fn(help='"annotations is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotationsMixin(annotations): { spec+: { target+: { configMap+: { metadata+: { annotations+: annotations } } } } },
          '#withLabels':: d.fn(help='"labels is a key value map to be copied to the target."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { spec+: { target+: { configMap+: { metadata+: { labels: labels } } } } },
          '#withLabelsMixin':: d.fn(help='"labels is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { spec+: { target+: { configMap+: { metadata+: { labels+: labels } } } } },
        },
        '#withData':: d.fn(help="\"data is the specification of the object's `data` field.\"", args=[d.arg(name='data', type=d.T.array)]),
        withData(data): { spec+: { target+: { configMap+: { data: if std.isArray(v=data) then data else [data] } } } },
        '#withDataMixin':: d.fn(help="\"data is the specification of the object's `data` field.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='data', type=d.T.array)]),
        withDataMixin(data): { spec+: { target+: { configMap+: { data+: if std.isArray(v=data) then data else [data] } } } },
      },
      '#namespaceSelector':: d.obj(help='"namespaceSelector specifies the namespaces where target resources will be synced."'),
      namespaceSelector: {
        '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
        matchExpressions: {
          '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressions(matchExpressions): { spec+: { target+: { namespaceSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } },
        '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
        withMatchExpressionsMixin(matchExpressions): { spec+: { target+: { namespaceSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } },
        '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { target+: { namespaceSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { target+: { namespaceSelector+: { matchLabels+: matchLabels } } } },
      },
      '#secret':: d.obj(help='"secret is the target Secret in Namespaces that all Bundle source data will be synced to.\\nUsing Secrets as targets is only supported if enabled at trust-manager startup.\\nBy default, trust-manager has no permissions for writing to secrets and can only read secrets in the trust namespace."'),
      secret: {
        '#data':: d.obj(help="\"data is the specification of the object's `data` field.\""),
        data: {
          '#withFormat':: d.fn(help='"format defines the format of the target value.\\nThe default format is PEM."', args=[d.arg(name='format', type=d.T.string)]),
          withFormat(format): { format: format },
          '#withKey':: d.fn(help="\"key is the key of the entry in the object's `data` field to be used.\"", args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withPassword':: d.fn(help='"password for PKCS12 trust store.\\nBy default, no password is used (password-less PKCS#12)."', args=[d.arg(name='password', type=d.T.string)]),
          withPassword(password): { password: password },
          '#withProfile':: d.fn(help='"profile specifies the certificate encryption algorithms and the HMAC algorithm\\nused to create the PKCS12 trust store.\\n\\nIf provided, allowed values are:\\n`LegacyRC2`: Deprecated. Not supported by default in OpenSSL 3 or Java 20.\\n`LegacyDES`: Less secure algorithm. Use this option for maximal compatibility.\\n`Modern2023`: Secure algorithm. Use this option in case you have to always use secure algorithms (e.g. because of company policy).\\n\\nDefault value is `LegacyDES`."', args=[d.arg(name='profile', type=d.T.string)]),
          withProfile(profile): { profile: profile },
        },
        '#metadata':: d.obj(help='"metadata is an optional set of labels and annotations to be copied to the target."'),
        metadata: {
          '#withAnnotations':: d.fn(help='"annotations is a key value map to be copied to the target."', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotations(annotations): { spec+: { target+: { secret+: { metadata+: { annotations: annotations } } } } },
          '#withAnnotationsMixin':: d.fn(help='"annotations is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotationsMixin(annotations): { spec+: { target+: { secret+: { metadata+: { annotations+: annotations } } } } },
          '#withLabels':: d.fn(help='"labels is a key value map to be copied to the target."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { spec+: { target+: { secret+: { metadata+: { labels: labels } } } } },
          '#withLabelsMixin':: d.fn(help='"labels is a key value map to be copied to the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { spec+: { target+: { secret+: { metadata+: { labels+: labels } } } } },
        },
        '#withData':: d.fn(help="\"data is the specification of the object's `data` field.\"", args=[d.arg(name='data', type=d.T.array)]),
        withData(data): { spec+: { target+: { secret+: { data: if std.isArray(v=data) then data else [data] } } } },
        '#withDataMixin':: d.fn(help="\"data is the specification of the object's `data` field.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='data', type=d.T.array)]),
        withDataMixin(data): { spec+: { target+: { secret+: { data+: if std.isArray(v=data) then data else [data] } } } },
      },
    },
    '#withInLineCAs':: d.fn(help='"inLineCAs is a simple string to append as the source data."', args=[d.arg(name='inLineCAs', type=d.T.string)]),
    withInLineCAs(inLineCAs): { spec+: { inLineCAs: inLineCAs } },
    '#withSourceRefs':: d.fn(help='"sourceRefs is a list of references to resources whose data will be appended and synced into\\nthe bundle target resources."', args=[d.arg(name='sourceRefs', type=d.T.array)]),
    withSourceRefs(sourceRefs): { spec+: { sourceRefs: if std.isArray(v=sourceRefs) then sourceRefs else [sourceRefs] } },
    '#withSourceRefsMixin':: d.fn(help='"sourceRefs is a list of references to resources whose data will be appended and synced into\\nthe bundle target resources."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceRefs', type=d.T.array)]),
    withSourceRefsMixin(sourceRefs): { spec+: { sourceRefs+: if std.isArray(v=sourceRefs) then sourceRefs else [sourceRefs] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
