package utils

type ProblemDetails struct {
	//   Type is a URI reference [RFC3986] that identifies the
	//   problem type. This specification encourages that, when
	//   dereferenced, it provide human-readable documentation for the
	//   problem type (e.g., using HTML [W3C.REC-html5-20141028]). When
	//   this member is not present, its value is assumed to be
	//   "about:blank".
	Type string `json:"type" xml:"type"`
	//   Title is a short, human-readable summary of the problem
	//   type. It SHOULD NOT change from occurrence to occurrence of the
	//   problem, except for purposes of localization (e.g., using
	//   proactive content negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title" xml:"title"`
	//   Status is the HTTP status code ([RFC7231], Section 6)
	//   generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty" xml:"status,omitempty"`
	//   Detail is a human-readable explanation specific to this
	//   occurrence of the problem. It is empty by default and
	//   it will not be marshalled if empty.
	Detail string `json:"detail,omitempty" xml:"detail,omitempty"`
	//   Instance is a URI reference that identifies the specific
	//   occurrence of the problem. It may or may not yield further
	//   information if dereferenced. It is empty by default and
	//   it will not be marshalled if empty.
	Instance string `json:"instance,omitempty" xml:"instance,omitempty"`
}

func (p *ProblemDetails) WithType(t string) *ProblemDetails {
	p.Type = t
	return p
}

func (p *ProblemDetails) WithTitle(title string) *ProblemDetails {
	p.Title = title
	return p
}

func (p *ProblemDetails) WithStatus(status int) *ProblemDetails {
	p.Status = status
	return p
}

func (p *ProblemDetails) WithDetail(detail string) *ProblemDetails {
	p.Detail = detail
	return p
}

func (p *ProblemDetails) WithInstance(instance string) *ProblemDetails {
	p.Instance = instance
	return p
}
func (p *ProblemDetails) ForGin() (int, *ProblemDetails) {
	return p.Status, p
}

func NewProblemDetails(status int) *ProblemDetails {
	return &ProblemDetails{
		Status: status,
	}
}
