{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='beyondtrustWorkloadCredentialsDynamicSecret', url='', help='"BeyondtrustWorkloadCredentialsDynamicSecret represents a generator that requests dynamic credentials from BeyondTrust Workload Credentials.\\nThis generator calls the BeyondTrust Workload Credentials API to generate fresh, temporary credentials\\n(such as AWS STS credentials) each time an ExternalSecret is refreshed.\\nDynamic secret definitions must be created in BeyondTrust Workload Credentials before they can be referenced.\\nFor complete documentation, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of BeyondtrustWorkloadCredentialsDynamicSecret', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'generators.external-secrets.io/v1alpha1',
    kind: 'BeyondtrustWorkloadCredentialsDynamicSecret',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"BeyondtrustWorkloadCredentialsDynamicSecretSpec defines the desired spec for BeyondtrustWorkloadCredentials dynamic generator.\\nThis generator enables obtaining temporary, short-lived credentials from BeyondTrust Workload Credentials.\\nFor more information, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api"'),
  spec: {
    '#provider':: d.obj(help='"Provider contains the BeyondtrustWorkloadCredentials provider configuration including authentication,\\nserver connection details, and the folder path to the dynamic secret definition.\\nThe folderPath should point to a dynamic secret definition that has been created in\\nBeyondTrust Workload Credentials (e.g., \\"production/aws-temp\\").\\nFor setup details, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api"'),
    provider: {
      '#auth':: d.obj(help='"Auth configures how the Operator authenticates with the BeyondTrust Workload Credentials API.\\nCurrently supports API key authentication via Kubernetes secret reference.\\nFor authentication setup, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api#authentication"'),
      auth: {
        '#apikey':: d.obj(help='"APIKey configures API token authentication for BeyondTrust Workload Credentials.\\nThe token is retrieved from a Kubernetes secret and used as a Bearer token for API requests."'),
        apikey: {
          '#token':: d.obj(help='"Token references the Kubernetes secret containing the BeyondTrust Workload Credentials API token.\\nThe secret should contain the API key used to authenticate with BeyondTrust Workload Credentials.\\nCreate an API token in your BeyondTrust Workload Credentials console and store it in a Kubernetes secret.\\nFor details on creating API tokens, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api#authentication"'),
          token: {
            '#withKey':: d.fn(help='"A key in the referenced Secret.\\nSome instances of this field may be defaulted, in others it may be required."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { provider+: { auth+: { apikey+: { token+: { key: key } } } } } },
            '#withName':: d.fn(help='"The name of the Secret resource being referred to."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { provider+: { auth+: { apikey+: { token+: { name: name } } } } } },
            '#withNamespace':: d.fn(help='"The namespace of the Secret resource being referred to.\\nIgnored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { spec+: { provider+: { auth+: { apikey+: { token+: { namespace: namespace } } } } } },
          },
        },
      },
      '#caProvider':: d.obj(help='"CAProvider points to a Secret or ConfigMap containing a PEM-encoded CA certificate.\\nThis is used to validate the BeyondTrust Workload Credentials API TLS certificate.\\nUse this as an alternative to CABundle when you want to reference an existing Kubernetes resource."'),
      caProvider: {
        '#withKey':: d.fn(help='"The key where the CA certificate can be found in the Secret or ConfigMap."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { provider+: { caProvider+: { key: key } } } },
        '#withName':: d.fn(help='"The name of the object located at the provider type."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { provider+: { caProvider+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The namespace the Provider type is in.\\nCan only be defined when used in a ClusterSecretStore."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { provider+: { caProvider+: { namespace: namespace } } } },
        '#withType':: d.fn(help='"The type of provider to use such as \\"Secret\\", or \\"ConfigMap\\"."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { provider+: { caProvider+: { type: type } } } },
      },
      '#server':: d.obj(help='"Server configures the BeyondTrust Workload Credentials server connection details.\\nIncludes the API URL and Site ID for your BeyondTrust instance.\\nFor API reference, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api"'),
      server: {
        '#withApiUrl':: d.fn(help='"APIURL is the base URL of your BeyondTrust Workload Credentials API server.\\nThis should be the full URL to your BeyondTrust instance.\\nExample: https://api.beyondtrust.io/siie\\nFor more information, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api#base-url"', args=[d.arg(name='apiUrl', type=d.T.string)]),
        withApiUrl(apiUrl): { spec+: { provider+: { server+: { apiUrl: apiUrl } } } },
        '#withSiteId':: d.fn(help='"SiteID is your BeyondTrust Workload Credentials site identifier (UUID format).\\nThis identifier is unique to your BeyondTrust Workload Credentials instance.\\nYou can find your Site ID in the BeyondTrust Workload Credentials admin console.\\nExample: a1b2c3d4-e5f6-4890-abcd-ef1234567890\\nFor more information, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api"', args=[d.arg(name='siteId', type=d.T.string)]),
        withSiteId(siteId): { spec+: { provider+: { server+: { siteId: siteId } } } },
      },
      '#withCaBundle':: d.fn(help="\"CABundle is a base64-encoded CA certificate used to validate the BeyondTrust Workload Credentials API TLS certificate.\\nUse this when your BeyondTrust instance uses a self-signed certificate or internal CA.\\nIf not set, the system's trusted root certificates are used.\"", args=[d.arg(name='caBundle', type=d.T.string)]),
      withCaBundle(caBundle): { spec+: { provider+: { caBundle: caBundle } } },
      '#withFolderPath':: d.fn(help='"FolderPath specifies the default folder path for secret retrieval.\\nSecrets will be fetched from this folder unless overridden in the ExternalSecret spec.\\nExample: \\"production/database\\" or \\"dev/api-keys\\"\\nLeave empty to retrieve secrets from the root folder.\\nFor folder organization, see: https://docs.beyondtrust.com/bt-docs/docs/secrets-api#folders"', args=[d.arg(name='folderPath', type=d.T.string)]),
      withFolderPath(folderPath): { spec+: { provider+: { folderPath: folderPath } } },
    },
    '#retrySettings':: d.obj(help='"RetrySettings configures exponential backoff for failed API requests.\\nIf not specified, uses the default retry settings."'),
    retrySettings: {
      '#withMaxRetries':: d.fn(help='', args=[d.arg(name='maxRetries', type=d.T.integer)]),
      withMaxRetries(maxRetries): { spec+: { retrySettings+: { maxRetries: maxRetries } } },
      '#withRetryInterval':: d.fn(help='', args=[d.arg(name='retryInterval', type=d.T.string)]),
      withRetryInterval(retryInterval): { spec+: { retrySettings+: { retryInterval: retryInterval } } },
    },
    '#withController':: d.fn(help='"Controller selects the controller that should handle this generator.\\nLeave empty to use the default controller."', args=[d.arg(name='controller', type=d.T.string)]),
    withController(controller): { spec+: { controller: controller } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
