// generated by AI.
{
  local this = self,
  local helmHookKeys = ['helm.sh/hook', 'helm.sh/hook-delete-policy', 'helm.sh/hook-weight'],

  // stripHelmHooks recursively walks an object tree produced by helm.template(),
  // strips helm.sh/* annotations (meaningless outside Helm lifecycle), and ensures
  // Jobs have spec.ttlSecondsAfterFinished for native K8s cleanup.
  stripHelmHooks(object, ttl=120)::
    if std.isObject(object)
    then
      if std.objectHas(object, 'apiVersion') && std.objectHas(object, 'kind')
      then this._processK8sObject(object, ttl)
      else
        std.mapWithKey(
          function(key, obj)
            this.stripHelmHooks(obj, ttl),
          object
        )
    else if std.isArray(object)
    then
      std.map(
        function(obj)
          this.stripHelmHooks(obj, ttl),
        object
      )
    else object,

  _hasHelmHooks(obj)::
    std.objectHas(obj, 'metadata')
    && std.isObject(obj.metadata)
    && std.objectHas(obj.metadata, 'annotations')
    && std.isObject(obj.metadata.annotations)
    && std.any([
      std.objectHas(obj.metadata.annotations, k)
      for k in helmHookKeys
    ]),

  _stripAnnotations(annotations)::
    {
      [k]: annotations[k]
      for k in std.objectFields(annotations)
      if !std.startsWith(k, 'helm.sh/')
    },

  _processK8sObject(obj, ttl)::
    if this._hasHelmHooks(obj)
    then
      local stripped = obj {
        metadata+: {
          annotations: this._stripAnnotations(obj.metadata.annotations),
        },
      };
      if obj.kind == 'Job'
      then
        stripped {
          spec+: {
            ttlSecondsAfterFinished:
              if std.objectHas(obj.spec, 'ttlSecondsAfterFinished')
              then obj.spec.ttlSecondsAfterFinished
              else ttl,
          },
        }
      else stripped
    else obj,
}
